
# Royal Home Ghana - Netlify configuration file

[build]
  # Directory to change to before starting a build
  base = "/"
  # Directory that contains the deploy-ready HTML files and assets
  publish = "dist"
  # Build command
  command = "npm run build"
  # Site ID for deployment
  site_id = "53095722-cb2b-455b-b343-4e0160044a97"

# Handle SPA routing - redirect all paths to index.html
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# Environment variables for production (you can also set these in Netlify UI)
[build.environment]
  NODE_VERSION = "18.16.0"
  SITE_NAME = "Royal Home Ghana"
  VITE_SUPABASE_URL = "https://brvpslvsckjweenkyaxa.supabase.co"
  VITE_SUPABASE_ANON_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImJydnBzbHZzY2tqd2Vlbmt5YXhhIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDU0NDM2MzMsImV4cCI6MjA2MTAxOTYzM30.w-6cK_0_rhyPehMa9nsZSMLH8Yw30zTUFsilWoSrXd0"

# Optimize asset caching
[[headers]]
  for = "/assets/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

# Configure secrets scanning
[secrets]
  SECRETS_SCAN_OMIT_KEYS = [
    "VITE_SUPABASE_URL",
    "VITE_SUPABASE_ANON_KEY"
  ]
  SECRETS_SCAN_OMIT_PATHS = [
    "dist/**/*",
    ".env*",
    "src/lib/supabase.ts"
  ]
  # Only scan specific file types
  SECRETS_SCAN_FILE_EXTENSIONS = [".js", ".ts", ".jsx", ".tsx", ".json", ".env"]
