
// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

// Use environment variables if available, otherwise use these default values for development
const SUPABASE_URL = import.meta.env.VITE_SUPABASE_URL || 'https://brvpslvsckjweenkyaxa.supabase.co';
const SUPABASE_ANON_KEY = import.meta.env.VITE_SUPABASE_ANON_KEY || 'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImJydnBzbHZzY2tqd2Vlbmt5YXhhIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDU0NDM2MzMsImV4cCI6MjA2MTAxOTYzM30.w-6cK_0_rhyPehMa9nsZSMLH8Yw30zTUFsilWoSrXd0';

// Verify environment variables are available but don't throw an error in development
if (!SUPABASE_URL || !SUPABASE_ANON_KEY) {
  console.warn('Missing Supabase environment variables. Using fallback values for development. Please check your .env file or Netlify environment variables in production.');
}

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_ANON_KEY);
