// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://brvpslvsckjweenkyaxa.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImJydnBzbHZzY2tqd2Vlbmt5YXhhIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDU0NDM2MzMsImV4cCI6MjA2MTAxOTYzM30.w-6cK_0_rhyPehMa9nsZSMLH8Yw30zTUFsilWoSrXd0";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);